cursor #dde4e3
cursor_text_color #bec8c8

foreground            #dde4e3
background            #0e1415
selection_foreground  #1b3435
selection_background  #b0cccc
url_color             #80d4d7

color0   #0e1415
color1   #f76f9f
color2   #6bd774
color3   #fff472
color4   #69c8cc
color5   #196063
color6   #80d4d7
color7   #d4e1e1
color8   #818b8b
color9   #ff9fc1
color10  #a5ffad
color11  #fff8a5
color12  #9be9ec
color13  #b6fcff
color14  #d0fdff
color15  #f8feff
