[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true
linemode = "size_and_mtime"

[preview]
wrap = "yes"
max_width = 2000
max_height = 2000

[tasks]
image_alloc = 1073741824

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$1"', orphan = true, desc = "Open", for = "linux" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { mime = "{audio,video}/*", use = "play" },
  { url = "*.json", use = "edit" },
  { url = "*.md", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.yaml", use = "edit" },
  { url = "*.yml", use = "edit" },
]

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]

prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
