-- ================================================================================================
-- TITLE : nightfox.nvim
-- ABOUT : Duskfox colorscheme with transparent background support.
-- LINKS :
--   > github : https://github.com/EdenEast/nightfox.nvim
-- ================================================================================================

return {
	{
		"EdenEast/nightfox.nvim",
		lazy = false,
		priority = 999,
		config = function()
			local palette = require("nightfox.palette").load("duskfox")
			local popup_bg = "None"
			local popup_border = palette.cyan.base
			local tree_bg = "None"
			local tree_cursor = "#282C34"

			require("nightfox").setup({
				options = {
					transparent = true,
				},
				groups = {
					duskfox = {
						Visual = { bg = palette.bg1 },
						CursorLine = { bg = "None" },
						Cursor = { fg = palette.bg0, bg = palette.white.base },
						lCursor = { fg = palette.bg0, bg = palette.cyan.base },
						TermCursor = { fg = palette.bg0, bg = palette.white.base },
						CursorLineNr = { fg = palette.yellow.base, style = "bold" },
						FloatBorder = { fg = popup_border, bg = popup_bg },
						FloatTitle = { fg = palette.cyan.base, bg = popup_bg, style = "bold" },
						FloatFooter = { fg = palette.fg3, bg = popup_bg },
						NormalFloat = { fg = palette.fg1, bg = popup_bg },
						NvimTreeNormal = { fg = palette.fg1, bg = tree_bg },
						NvimTreeNormalNC = { fg = palette.fg2, bg = tree_bg },
						NvimTreeEndOfBuffer = { fg = palette.bg0, bg = tree_bg },
						NvimTreeCursorLine = { bg = tree_cursor },
						NvimTreeWinSeparator = { fg = palette.cyan.dim, bg = tree_bg },
						NvimTreeIndentMarker = { fg = palette.bg3, bg = tree_bg },
						NvimTreeFolderArrowClosed = { fg = palette.fg3, bg = tree_bg },
						NvimTreeFolderArrowOpen = { fg = palette.cyan.dim, bg = tree_bg },
						NvimTreeFolderIcon = { fg = palette.blue.base, bg = tree_bg },
						NvimTreeFolderName = { fg = palette.fg2, bg = tree_bg },
						NvimTreeOpenedFolderName = { fg = palette.cyan.base, bg = tree_bg, style = "bold" },
						NvimTreeFileIcon = { fg = palette.fg2, bg = tree_bg },
						NvimTreeGitDirty = { fg = palette.yellow.base, bg = tree_bg },
						NvimTreeGitNew = { fg = palette.green.base, bg = tree_bg },
						NvimTreeGitDeleted = { fg = palette.red.base, bg = tree_bg },
						NvimTreeGitRenamed = { fg = palette.magenta.base, bg = tree_bg },
						NvimTreeGitIgnored = { fg = palette.fg3, bg = tree_bg },
						FzfLuaNormal = { fg = palette.fg1, bg = popup_bg },
						FzfLuaBorder = { fg = popup_border, bg = popup_bg },
						FzfLuaTitle = { fg = palette.cyan.base, bg = popup_bg, style = "bold" },
						FzfLuaPreviewNormal = { fg = palette.fg1, bg = popup_bg },
						FzfLuaPreviewBorder = { fg = popup_border, bg = popup_bg },
						FzfLuaPreviewTitle = { fg = palette.yellow.base, bg = popup_bg, style = "bold" },
						FzfLuaCursorLine = { bg = palette.sel0 },
						FzfLuaCursorLineNr = { fg = palette.yellow.base, bg = palette.sel0, style = "bold" },
						FzfLuaSearch = { fg = palette.yellow.base, style = "bold" },
						FzfLuaHeaderBind = { fg = palette.yellow.base },
						FzfLuaHeaderText = { fg = palette.fg3 },
						FzfLuaFzfPrompt = { fg = palette.cyan.base, bg = popup_bg, style = "bold" },
						FzfLuaFzfPointer = { fg = palette.yellow.base, bg = popup_bg, style = "bold" },
						FzfLuaFzfMarker = { fg = palette.green.base, bg = popup_bg, style = "bold" },
						FzfLuaFzfInfo = { fg = palette.comment, bg = popup_bg },
						FzfLuaFzfMatch = { fg = palette.cyan.bright, bg = popup_bg, style = "bold" },
						FzfLuaFzfScrollbar = { fg = palette.blue.base, bg = popup_bg },
						BlinkCmpMenu = { fg = palette.fg1, bg = popup_bg },
						BlinkCmpMenuBorder = { fg = popup_border, bg = popup_bg },
						BlinkCmpMenuSelection = { fg = palette.fg0, bg = palette.sel0, style = "bold" },
						BlinkCmpLabel = { fg = palette.fg1 },
						BlinkCmpLabelMatch = { fg = palette.cyan.bright, style = "bold" },
						BlinkCmpLabelDetail = { fg = palette.fg3 },
						BlinkCmpLabelDescription = { fg = palette.fg3, style = "italic" },
						BlinkCmpSource = { fg = palette.comment, style = "italic" },
						BlinkCmpScrollBarThumb = { bg = palette.bg4 },
						BlinkCmpScrollBarGutter = { bg = popup_bg },
						BlinkCmpDoc = { fg = palette.fg1, bg = popup_bg },
						BlinkCmpDocBorder = { fg = popup_border, bg = popup_bg },
						BlinkCmpDocSeparator = { fg = palette.bg3, bg = popup_bg },
						BlinkCmpDocCursorLine = { bg = palette.sel0 },
						BlinkCmpSignatureHelp = { fg = palette.fg1, bg = popup_bg },
						BlinkCmpSignatureHelpBorder = { fg = popup_border, bg = popup_bg },
						BlinkCmpSignatureHelpActiveParameter = { fg = palette.yellow.base, style = "bold,underline" },
						Pmenu = { fg = palette.fg1, bg = popup_bg },
						PmenuSel = { fg = palette.fg0, bg = palette.sel0, style = "bold" },
						PmenuSbar = { bg = popup_bg },
						PmenuThumb = { bg = palette.bg4 },
						WinSeparator = { fg = palette.bg4 },
						TabLine = { fg = palette.fg3, bg = "None" },
						TabLineFill = { bg = "None" },
						TabLineSel = { fg = palette.cyan.base, bg = "None", style = "bold" },
						StatusLine = { fg = palette.fg1, bg = palette.bg1 },
						StatusLineNC = { fg = palette.fg3, bg = palette.bg0 },
						MsgArea = { fg = palette.fg1, bg = "None" },
						ModeMsg = { fg = palette.yellow.base, bg = "None", style = "bold" },
						MsgSeparator = { fg = palette.bg4, bg = "None" },
						MiniTrailspace = { bg = "None" },
						DropBarMenuNormalFloat = { fg = palette.fg1, bg = popup_bg },
						DropBarMenuFloatBorder = { fg = popup_border, bg = popup_bg },
						DropBarCurrentContext = { fg = palette.yellow.base, style = "bold" },
						DropBarIconUIIndicator = { fg = palette.cyan.base },
						EdgyNormal = { fg = palette.fg1, bg = "None" },
						EdgyWinBar = { fg = palette.yellow.base, bg = "None", style = "bold" },
						EdgyTitle = { fg = palette.cyan.base, style = "bold" },
						SnacksDashboardNormal = { fg = palette.fg1, bg = "None" },
						SnacksDashboardHeader = { fg = palette.white.base, bg = "None", style = "bold" },
						SnacksDashboardIcon = { fg = palette.cyan.base, bg = "None" },
						SnacksDashboardDesc = { fg = palette.fg2, bg = "None" },
						SnacksDashboardDir = { fg = palette.yellow.base, bg = "None" },
						SnacksDashboardKey = { fg = palette.yellow.base, bg = "None", style = "bold" },
						SnacksDashboardFooter = { fg = palette.comment, bg = "None" },
						SnacksTerminal = { fg = palette.fg1, bg = "None" },
						SnacksTerminalBorder = { fg = popup_border, bg = "None" },
					},
				},
			})
			vim.cmd("colorscheme duskfox")
		end,
	},
}
